pipeline {
    agent {
        kubernetes {
      label 'mypodtemplate-v1'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven
    command:
    - cat
    tty: true
"""
        }
    }

    stages {
        stage('Hello') {
            steps {
                echo "Hello ${subjValue}"
            }
        }
    }
}